aws:
  region: ap-southeast-1
  ecrRepository: practical-devops-ecr
  accountId: "307946653621"

kubernetes:
  namespace: development
  
services:
  frontend:
    port: 3000
    healthCheckPath: /health
    memory: 512Mi
    cpu: 250m
  backend:
    port: 8080
    healthCheckPath: /actuator/health
    memory: 1Gi
    cpu: 500m